# VERIFY_2026-06-07_integrity-f04-f05-close.ps1 -- auto-generated by /wrap
$root = 'D:\aidirectory'
$run = 0; $pass = 0; $fails = @()

$files = @(
    'agents/n8n-workflow/MANIFEST.md',
    'HANDOVER.md',
    'HANDOVER_CODE.md'
)

# Existence checks
foreach ($f in $files) {
    $run++
    if (Test-Path (Join-Path $root $f)) { $pass++ }
    else { $fails += "FAIL: MISSING $f" }
}

# Content spot-checks
$manifestContent = Get-Content (Join-Path $root 'agents/n8n-workflow/MANIFEST.md') -Raw -ErrorAction SilentlyContinue
if ($manifestContent) {
    $run++
    if ($manifestContent -match 'executionOrder') { $pass++ }
    else { $fails += "FAIL: MANIFEST missing PUT body rule (executionOrder)" }

    $run++
    if ($manifestContent -match 'HTTP Request node') { $pass++ }
    else { $fails += "FAIL: MANIFEST missing Code-node HTTP absence note" }
}

$handoverContent = Get-Content (Join-Path $root 'HANDOVER.md') -Raw -ErrorAction SilentlyContinue
if ($handoverContent) {
    $run++
    if ($handoverContent -match 'executionOrder') { $pass++ }
    else { $fails += "FAIL: HANDOVER.md missing n8n PUT fragility entry" }
}

Write-Output "TESTS: $run run $pass passed"
$fails | ForEach-Object { Write-Output $_ }
exit $(if ($fails.Count -eq 0) { 0 } else { 1 })
