# VERIFY_2026-06-07_integrity-findings-apply.ps1 -- auto-generated by /wrap
$root = 'D:\aidirectory'
$run = 0; $pass = 0; $fails = @()

$files = @(
    'CLAUDE.md',
    'HANDOVER.md'
)

# Existence checks
foreach ($f in $files) {
    $run++
    if (Test-Path (Join-Path $root $f)) { $pass++ }
    else { $fails += "FAIL: MISSING $f" }
}

# .ps1 syntax checks
foreach ($f in ($files | Where-Object { $_ -like '*.ps1' })) {
    $full = Join-Path $root $f
    if (Test-Path $full) {
        $run++
        $errs = $null
        $null = [System.Management.Automation.Language.Parser]::ParseFile($full, [ref]$null, [ref]$errs)
        if ($errs.Count -eq 0) { $pass++ } else { $fails += "FAIL: SYNTAX $f" }
    }
}

# .md command files: check @-referenced paths exist
foreach ($f in ($files | Where-Object { $_ -like '.claude/commands/*.md' })) {
    $content = Get-Content (Join-Path $root $f) -Raw -ErrorAction SilentlyContinue
    if ($content) {
        [regex]::Matches($content, '@([\w/\\.\-]+)') | ForEach-Object {
            $ref = $_.Groups[1].Value
            $run++
            if (Test-Path (Join-Path $root $ref)) { $pass++ }
            else { $fails += "FAIL: REF_MISSING $ref (in $f)" }
        }
    }
}

Write-Output "TESTS: $run run $pass passed"
$fails | ForEach-Object { Write-Output $_ }
exit $(if ($fails.Count -eq 0) { 0 } else { 1 })
